### ISSUE TITLE
SDL 1.x audio hangs, PulseAudio pthread_join hang, audio stutter, and changing the SDL output driver is impossible once past SDL_Init.

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#302]
Occasionally, SDL 1.x (or DOSBox-X?) hangs on shutdown when SDL 1.x has decided to talk to PulseAudio instead of ALSA. Sometimes before the hang, audio will halt and repeat.

**Comment by joncampbell123** [comment]
I've also noticed that when PulseAudio is running, the DMA counter in the guest can make large jumps at the beginning of a DSP block in Sound Blaster emulation. Doesn't happen when SDL is using ALSA.

**Comment by joncampbell123** [comment]
In the same manner that Windows builds force video to "surface" I added code in Linux (when targeting SDL 1.x) to force audio to the "alsa" driver to avoid this hang.

Most Linux distributions configure ALSA to default to using a plugin that connects to Pulseaudio anyway. ALSA support is much more stable than SDL 1.x support for Pulseaudio.

I will close this ticket if the modification proves to resolve the issue.

**Comment by joncampbell123** [comment]
Compiling SDL 1.x directly into DOSBox-X seems to have magically solved PulseAudio crashes, hmm.

**Comment by joncampbell123** [comment]
Oh look, the bug came back 10 minutes after posting the last report. Gee, how predictable.

**Comment by joncampbell123** [comment]
Demo testing with PulseAudio support statically compiled so far has not reproduced the hang/crash.

I just announced my confidence. Bring it on Murphy's law!

**Comment by joncampbell123** [comment]
Hasn't hit yet, but I did get one assert fail within PulseAudio:

    Assertion 't = find_next_time_event(m)' failed at pulse/mainloop.c:719, function calc_next_timeout(). Aborting.

**Comment by joncampbell123** [comment]
Nope. It only took one hour of toying around to hit again.

If PulseAudio keeps this up I'll just disable PulseAudio SDL output entirely in my builds. I have no tolerance for this shit.

**Comment by joncampbell123** [comment]
The latest commit on Linux strongly encourages SDL to use ALSA audio output now. Concessions are made for ALSA installations that have an ALSA to PulseAudio plugins. Other than that, do what it takes NOT to use PulseAudio.

**Comment by joncampbell123** [comment]
It still hung???????????

Is the SDL 1.x library itself unable to reconcile opening and closing audio???????

**Comment by joncampbell123** [comment]
Great, asking SDL to compile without threads disables audio output. Wonderful.

Looks like SDL 1.x support is going to have to rewrite audio thread handling because for whatever reason it can't seem to handle it properly. Opening and closing repeatedly seems to trigger a pthread_join hang in SDL_CloseAudio.

**Comment by joncampbell123** [comment]
Apparently I can break SDL audio output by calling SDL_CloseAudio() then SDL_OpenAudio() again.

**Comment by joncampbell123** [comment]
PulseAudio thread running despite directive to use ALSA??????? You sneaky bastard.

**Comment by joncampbell123** [comment]
Yup. My code sets SDL audio driver = ALSA and it goes and opens PulseAudio. So much for SDL_AUDIODRIVER. >:p

**Comment by joncampbell123** [comment]
Oh, ok. My code does senenv() to set SDL_AUDIODRIVER and SDL_getenv("SDL_AUDIODRIVER") == NULL. Why??

**Comment by joncampbell123** [comment]
Id   Target Id         Frame 
* 1    Thread 0x7f265ce5a760 (LWP 10606) "dosbox-x" mem_readb_inline (address=202929) at core_normal.cpp:232
  2    Thread 0x7f2650683700 (LWP 10607) "dosbox-x" 0x00007f265c56042d in nanosleep () from /lib64/libpthread.so.0
  3    Thread 0x7f264b75a700 (LWP 10609) "dosbox-x" 0x00007f265c55fd0d in read () from /lib64/libpthread.so.0

thread 1:
#0  mem_readb_inline (address=202929) at core_normal.cpp:232
#1  Fetchb () at core_normal.cpp:122
#2  CPU_Core_Normal_Run () at core_normal.cpp:174
#3  0x000000000041341e in Normal_Loop () at dosbox.cpp:360
#4  0x0000000000413a7e in DOSBOX_RunMachine () at dosbox.cpp:522
#5  0x0000000000634c6d in CALLBACK_RunRealInt (intnum=<optimized out>) at callback.cpp:165
#6  0x000000000047591f in DOS_Shell::Execute (this=<optimized out>, name=<optimized out>, args=<optimized out>) at shell_misc.cpp:773
#7  0x0000000000470643 in DOS_Shell::DoCommand (this=0x52c1b90, line=0x7ffe952d05f6 " @fluid.cfg") at shell_cmds.cpp:172
#8  0x0000000000468eba in DOS_Shell::ParseLine (this=0x52c1b90, line=0x7ffe952d05f0 "demovt @fluid.cfg") at shell.cpp:260
#9  0x00000000004693eb in DOS_Shell::Run (this=0x52c1b90) at shell.cpp:343
#10 0x000000000046a636 in SHELL_Run () at shell.cpp:886
#11 0x00000000004bddf6 in VM_Boot_DOSBox_Kernel () at sdlmain.cpp:4963
#12 0x00000000004927c3 in BIOS::cb_bios_boot__func () at bios.cpp:4976
#13 0x0000000000413445 in Normal_Loop () at dosbox.cpp:371
#14 0x0000000000413a7e in DOSBOX_RunMachine () at dosbox.cpp:522
#15 0x000000000040e08a in main (argc=<optimized out>, argv=<optimized out>) at sdlmain.cpp:5459

thread 2:
#0  0x00007f265c56042d in nanosleep () from /lib64/libpthread.so.0
#1  0x00000000007199b3 in SDL_Delay (ms=<optimized out>) at ./src/timer/unix/SDL_systimer.c:118
#2  0x00000000007199da in RunTimer (unused=<optimized out>) at ./src/timer/unix/SDL_systimer.c:203
#3  0x00000000006fd385 in SDL_RunThread (data=0x51d73c0) at ./src/thread/SDL_thread.c:204
#4  0x0000000000717979 in RunThread (data=<optimized out>) at ./src/thread/pthread/SDL_systhread.c:47
#5  0x00007f265c558e2c in start_thread () from /lib64/libpthread.so.0
#6  0x00007f2658dd6edd in clone () from /lib64/libc.so.6

thread 3:
#0  0x00007f265c55fd0d in read () from /lib64/libpthread.so.0
#1  0x00007f2652cbcbcf in read (__nbytes=10, __buf=0x7f264b759d70, __fd=6) at /usr/include/bits/unistd.h:45
#2  pa_read (fd=6, buf=0x7f264b759d70, count=10, type=<optimized out>) at pulsecore/core-util.c:433
#3  0x00007f2658066bc8 in pa_mainloop_prepare () from /usr/lib64/libpulse.so.0
#4  0x00007f26580675cd in pa_mainloop_iterate () from /usr/lib64/libpulse.so.0
#5  0x0000000000709a7c in PULSE_WaitAudio (this=0x524d0d0) at ./src/audio/pulse/SDL_pulseaudio.c:310
#6  0x00000000006f7442 in SDL_RunAudio (audiop=0x524d0d0) at ./src/audio/SDL_audio.c:222
#7  0x00000000006fd385 in SDL_RunThread (data=0x5268030) at ./src/thread/SDL_thread.c:204
#8  0x0000000000717979 in RunThread (data=<optimized out>) at ./src/thread/pthread/SDL_systhread.c:47
#9  0x00007f265c558e2c in start_thread () from /lib64/libpthread.so.0
#10 0x00007f2658dd6edd in clone () from /lib64/libc.so.6

**Comment by joncampbell123** [comment]
When building SDL 1.x with the builtin library, I went ahead and disabled PulseAudio. Use ALSA. Most Linux systems configure ALSA to hook into PulseAudio anyway.
