### ISSUE TITLE
Rendering bug since DOSBox-X 0.83.22

### ISSUE THREAD

**Issue by bugrepo** [joncampbell123/dosbox-x#3435]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 7 SP1

### What version(s) of DOSBox-X have this bug?

0.83.22-0.83.24

### Describe the bug

When I boot Windows NT 3.51 Setup Floppy, only TTF output works.

Surface, Direct3D, OpenGL don't work.

### Steps to reproduce the behaviour

1. Run DOSBox-X 0.83.22-0.83.24.
2. Boot from Windows NT 3.51 Setup Floppy.

**Comment by bugrepo** [comment]
But I spent few hours and found a workaround:
```
[render]
alt render = true
```

**Comment by Wengier** [comment]
I don't have Windows NT 3.51 Setup Floppy to test at this time. Perhaps you can do a ``git bisect`` and which commit caused the said issue?

**Comment by bugrepo** [comment]
I've updated my post with link to Windows NT 3.51 Setup Floppy.

Unfortunately, I'm not fully aware about `git bisect`, but I can tell, that version 0.83.21 doesn't have this bug.

**Comment by Jookia** [comment]
If you can build from source I'm happy to write some instructions for using git bisect to find the broken build.

**Comment by bugrepo** [comment]
@Jookia Could you please tell me, what is the most simple way to build it from sources?
I use FASM, so I hardly imagine, how to use all thees compilers, linkers and makers...
Is there some `autobuild.bat` like [this](https://github.com/leecher1337/ntvdmx64/tree/master/autobuild), which downloads everything needed and do all the job?

**Comment by Jookia** [comment]
Ah, it sounds like you can't build from source. I'll see if I can reproduce your error and bisect it.

That said, could you test under DOSBox 0.83.25?

**Comment by Jookia** [comment]
Bad commit seems to be a0c26c41060e11ebf930e097f8899bdaafc3e831

@grapeli discovered this too in https://github.com/joncampbell123/dosbox-x/issues/3463#issuecomment-1120193587

**Comment by Jookia** [comment]
It looks like calling ```real_readb(BIOSMEM_SEG,BIOSMEM_NB_ROWS);``` or ```real_readw(BIOSMEM_SEG,BIOSMEM_NB_COLS);``` is triggering a page fault. Here's a quick stacktrace of things gone awfully wrong:

```
#0  0x0000555555b27c86 in CPU_Core_Full_Run() () at core_full/load.h:19
#1  0x0000555555a734f6 in PageFaultCore() () at paging.cpp:110
#2  0x0000555555604bf6 in Normal_Loop() () at dosbox.cpp:356
#3  0x0000555555604e26 in DOSBOX_RunMachine() () at dosbox.cpp:630
#4  0x0000555555a73724 in PAGING_NewPageFault(PhysPt, Bitu, bool, Bitu)
    (lin_addr=1156, page_addr=323584, prepare_only=<optimised out>, faultcode=0) at paging.cpp:330
#5  0x0000555555a75cca in NewInitPageHandler::InitPage(unsigned int, bool, bool)
    (this=<optimised out>, lin_addr=lin_addr@entry=1156, writing=writing@entry=false, prepare_only=prepare_only@entry=false)
    at paging.cpp:824
#6  0x0000555555a75e3a in NewInitPageHandler::readb(unsigned int) (this=<optimised out>, addr=1156) at paging.cpp:702
#7  0x0000555555a050dd in real_readb (off=132, seg=64) at ../../include/mem.h:250
#8  EGAVGA_TEXT_Combined_Draw_Line<5, unsigned int>(Bitu, Bitu) (vidstart=3520, line=7) at vga_draw.cpp:2074
```

**Comment by Wengier** [comment]
I think this issue is already fixed in the current repository code (as fixed in commit https://github.com/joncampbell123/dosbox-x/pull/3472/commits/5172a1f07528e5e01df5261b3bdef4bf0f69ff6c). You can try the latest Windows builds below:

32-bit builds: https://github.com/joncampbell123/dosbox-x/suites/6423779505/artifacts/234677582
64-bit builds: https://github.com/joncampbell123/dosbox-x/suites/6423779506/artifacts/234677271

Hope this helps.

**Comment by Jookia** [comment]
Seems fixed now but it looks like you've just disabled the feature?

**Comment by Wengier** [comment]
@Jookia You meant I disabled the feature? No, I did not ever since it was recently fixed. You can surely try the current repository code too and see if it works for you.

**Comment by Jookia** [comment]
How do I make sure it works?

**Comment by Wengier** [comment]
FYI the internal DBCS support (for non-TTF outputs) is currently intended to be enabled for internal DOS shell only (and only in DBCS code pages with the help of DOS/V fonts), which is why I tried to disable it for guest systems (including LOADLIN environment) since I believe they do not need such support. You can also disable such support altogether with showdbcsnondosv option in [dosv] section.
