### ISSUE TITLE
Helix cloaking.exe crashes or terminates DOSBox-X when EMS is enabled

### ISSUE THREAD

**Issue by turol** [joncampbell123/dosbox-x#3455]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Debian testing

### What version(s) of DOSBox-X have this bug?

0.83.25

### Describe the bug

Running Helix multimedia cloaking.exe will either crash dosbox, error out or infinite loop depending on used core. This happens when EMS is enabled, which is the default.

### Expected behavior

Doesn't crash. Either clean exit or actually working and providing DPMS/cloaking services.

### Steps to reproduce the behaviour

1. Acquire cloaking.exe, for example from https://www.mdgx.com/drv.htm
2. Run it in dosbox

### Emulator log

```text
LOG: Early LOG Init complete
LOG: "65536" is not a valid value for variable: pcrate.
It might now be reset to the default value: 65536
LOG: DOSBox-X's working directory: /tmp/cloaktest
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG: DOSBox-X version 0.83.25 (Linux SDL2)
LOG: Host keyboard layout is now us (US English)
LOG: Mapper keyboard layout is now us (US English)
LOG: SDL2 reports desktop display mode 1920 x 1080
LOG: The default output for the video system: opengl
LOG: Configured windowposition: 
LOG: SDL: Current window pixel format: SDL_PIXELFORMAT_RGB888
LOG: SDL: You are running in 24 bpp mode, this will slow down things!
LOG: X11 main window is 640 x 400 maximized=0
LOG: X11 extension XRANDR is available
LOG: XRandR CRTC 4: pos=(0,0) size=(1920,1080) outputs=1
LOG: Our window lies on this CRTC display (window pos=(630,330) size=(640,400) match=(950,530)).
LOG:   Goes to output 0: name='eDP-1-1' size_mm=(344 x 194)
LOG: Screen report: Method 'XRandR' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (344.000 x 194.000 mm) (13.543 x 7.638 in) (141.767 x 141.402 DPI)
LOG: ISA BCLK: 8333333.333Hz (25000000/3)
LOG: monopal: green, 
LOG: Active save slot: 1 [Empty]
LOG: USING AVI+ZMBV
LOG: Max 3670016 sz 16384
LOG: Final 16384
LOG: SDLNet_TCP_Open: Couldn't connect to remote host
LOG: TiMidity: can't open control connection (host=127.0.0.1, port=7777)
fluidsynth: error: Unknown numeric setting 'audio.periods'
fluidsynth: error: Unknown numeric setting 'audio.period-size'
fluidsynth: error: Unknown string setting 'synth.reverb.active'
fluidsynth: error: Unknown string setting 'synth.chorus.active'
fluidsynth: Using PulseAudio driver
fluidsynth: warning: Failed to set thread to high priority
LOG: MIDI:fluidsynth: Loaded SoundFont: /usr/share/sounds/sf2/FluidR3_GM.sf2
LOG: MIDI:Opened device:fluidsynth
LOG: Pentium CMPXCHG8B emulation is enabled
LOG: VOODOO LFB now at d0000000
LOG: Serial1: BASE 3f8h
LOG: Serial2: BASE 2f8h
LOG: Parallel1: BASE 378h
LOG: MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h
LOG: GetDesktopResolution reading X11 desktop resolution
LOG: Root window (ID 660) is 1920 x 1080
LOG: X11 main window is 640 x 400 maximized=0
LOG: XRandR CRTC 4: pos=(0,0) size=(1920,1080) outputs=1
LOG: Our window lies on this CRTC display (window pos=(630,330) size=(640,400) match=(950,530)).
LOG:   Goes to output 0: name='eDP-1-1' size_mm=(344 x 194)
LOG: Screen report: Method 'XRandR' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (344.000 x 194.000 mm) (13.543 x 7.638 in) (141.767 x 141.402 DPI)
LOG: Allocated APM BIOS pm entry point at f000:ce20
LOG: Writing code to fce20
LOG: Writing code to fce40
LOG: X11 main window is 640 x 400 maximized=0
LOG: XRandR CRTC 4: pos=(0,0) size=(1920,1080) outputs=1
LOG: Our window lies on this CRTC display (window pos=(630,330) size=(640,400) match=(950,530)).
LOG:   Goes to output 0: name='eDP-1-1' size_mm=(344 x 194)
LOG: Screen report: Method 'XRandR' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (344.000 x 194.000 mm) (13.543 x 7.638 in) (141.767 x 141.402 DPI)
LOG: ISA Plug & Play BIOS enabled
LOG: VGA ROM BIOS init callback
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: X11 main window is 640 x 497 maximized=0
LOG: XRandR CRTC 4: pos=(0,0) size=(1920,1080) outputs=1
LOG: Our window lies on this CRTC display (window pos=(630,330) size=(640,497) match=(950,578)).
LOG:   Goes to output 0: name='eDP-1-1' size_mm=(344 x 194)
LOG: Screen report: Method 'XRandR' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (344.000 x 194.000 mm) (13.543 x 7.638 in) (141.767 x 141.402 DPI)
LOG: font texture id=2 will make 128 x 256
LOG: X11 main window is 640 x 497 maximized=0
LOG: XRandR CRTC 4: pos=(0,0) size=(1920,1080) outputs=1
LOG: Our window lies on this CRTC display (window pos=(626,253) size=(640,497) match=(946,501)).
LOG:   Goes to output 0: name='eDP-1-1' size_mm=(344 x 194)
LOG: Screen report: Method 'XRandR' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (344.000 x 194.000 mm) (13.543 x 7.638 in) (141.767 x 141.402 DPI)
LOG: WARNING: No translation support (to host) for code page 0
LOG:    2999862 ERROR BIOS:Keyboard layout file auto not found
LOG:    2999862 ERROR BIOS:Keyboard layout file auto not found
LOG: XMS: 50 handles allocated for use by the DOS environment
LOG: EMS page frame at 0xe000-0xefff
LOG: COMMAND.COM env size:             720 bytes
LOG: COMMAND.COM environment block:    0x0701 sz=0x002d
LOG: COMMAND.COM main body (PSP):      0x072f sz=0x009a
LOG: COMMAND.COM stack:                0x0749
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: X11 main window is 720 x 417 maximized=0
LOG: XRandR CRTC 4: pos=(0,0) size=(1920,1080) outputs=1
LOG: Our window lies on this CRTC display (window pos=(626,253) size=(720,417) match=(986,461)).
LOG:   Goes to output 0: name='eDP-1-1' size_mm=(344 x 194)
LOG: Screen report: Method 'XRandR' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (344.000 x 194.000 mm) (13.543 x 7.638 in) (141.767 x 141.402 DPI)
LOG: font texture id=2 will make 128 x 256
LOG: X11 main window is 720 x 417 maximized=0
LOG: XRandR CRTC 4: pos=(0,0) size=(1920,1080) outputs=1
LOG: Our window lies on this CRTC display (window pos=(586,293) size=(720,417) match=(946,501)).
LOG:   Goes to output 0: name='eDP-1-1' size_mm=(344 x 194)
LOG: Screen report: Method 'XRandR' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (344.000 x 194.000 mm) (13.543 x 7.638 in) (141.767 x 141.402 DPI)
LOG: SHELL:Redirect output to nul
LOG:    5930614 ERROR MISC:XMS: unknown function 7F
LOG: DOSBox-X has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox-X's options.
LOG: E_Exit: No byte handler for write to d88a
E_Exit: No byte handler for write to d88a
```

### Additional context

When EMS is enabled (the default):
Core auto crashes dosbox
Cores normal, simple and full exit with above error message.
Core dynamic results in infinite loop, have to close dosbox. Closes cleanly, no hang.
Core dynamic_rec causes different error
```
E_Exit: DynrecCore: illegal option in dyn_grp4_eb
```
Setting `ems=false` makes it not crash and claims success. Seems to work too, at least on `cacheclk.exe`.
Setting `xms=false` makes cloaking.exe cleanly error out, regardless of EMS state

Backtrace from auto core:
```
#0  0x000055f291d33467 in host_readd (off=0x7f24f4d47404 "") at ../../include/mem.h:126
#1  phys_readd (addr=50164) at ../../include/mem.h:201
#2  PAGING_MakePhysPage(unsigned long&) (page=page@entry=@0x7fff00711d08: 253) at paging.cpp:900
#3  0x000055f291dd25ff in MakeCodePage(Bitu, CodePageHandler*&) (lin_addr=lin_addr@entry=1036960, cph=@0x7fff00711d58: 0x0) at core_dyn_x86/decoder.h:108
#4  0x000055f291de835e in CPU_Core_Dyn_X86_Run() () at core_dyn_x86.cpp:320
#5  0x000055f2918cd696 in Normal_Loop() () at dosbox.cpp:357
#6  0x000055f2918cd89e in DOSBOX_RunMachine() () at dosbox.cpp:631
#7  0x000055f291d2002d in CALLBACK_RunRealInt(unsigned char) (intnum=intnum@entry=33 '!') at callback.cpp:209
#8  0x000055f291a34f2b in DOS_Shell::Execute(char*, char const*) (this=this@entry=0x55f29820d800, name=name@entry=0x7fff007134a0 "cloaking", args=args@entry=0x7fff007147f8 "") at shell_misc.cpp:1495
#9  0x000055f291a1bb21 in DOS_Shell::DoCommand(char*) (this=this@entry=0x55f29820d800, line=0x7fff007147f8 "", line@entry=0x7fff007147f0 "cloaking") at shell_cmds.cpp:277
#10 0x000055f291a032ed in DOS_Shell::ParseLine(char*) (this=0x55f29820d800, line=0x7fff007147f0 "cloaking") at shell.cpp:483
#11 0x000055f291a03d1b in DOS_Shell::Run() (this=0x55f29820d800) at shell.cpp:959
#12 0x000055f291a0d771 in SHELL_Run() () at shell.cpp:1836
#13 0x000055f291ace878 in VM_Boot_DOSBox_Kernel() () at sdlmain.cpp:7190
#14 0x000055f291a83d4f in BIOS::cb_bios_boot__func() () at bios.cpp:9587
#15 0x000055f2918cd6c8 in Normal_Loop() () at dosbox.cpp:372
#16 0x000055f2918cd89e in DOSBOX_RunMachine() () at dosbox.cpp:631
#17 0x000055f291887023 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at sdlmain.cpp:9020
```

**Comment by grapeli** [comment]
Segmentation fault also occurs in dosbox-SVN and dosbox-staging (default configuration).
