### ISSUE TITLE
Flatpak build crashes when opening debugger

### ISSUE THREAD

**Issue by Jookia** [joncampbell123/dosbox-x#3627]
### Describe the bug

The debugger crashes in the Flatpak build but not in a regular build

### Steps to reproduce the behaviour

1. Build the flatpak using make-flatpak.sh
2. Run it
3. Open debug menu

### Expected behavior

It should work the same way as a regular build

### What operating system(s) this bug have occurred on?

Ubuntu 22.04 amd64

### What version(s) of DOSBox-X have this bug?

0.84.1, d70cc15a3882ecbe420afedd30336b8e73d54243

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
I think pdcurses is being used for the flatpak, as that is in the /vs/ tree, and no curses package is defined in the yaml file. While for the RPM, ncurses is being used in the build. Perhaps I should try to build the flatpak also with ncurses.

**Comment by rderooy** [comment]
I just checked the flatpak build log, and it seems ncurses is being used for the official build.
```
checking for curses.h... yes
checking for initscr in -lcurses... yes
checking for initscr in -lncurses... yes
checking for initscr in -lpdcurses... no
```
I guess ncurses must be part of the runtime.

Do you have the same issue with the flatpak from flathub?
https://flathub.org/apps/details/com.dosbox_x.DOSBox-X

**Comment by Jookia** [comment]
This is using the Flatpak from Flathub and a locally built one.

**Comment by rderooy** [comment]
Ok, because I was able to open the debugger from the flathub hosted build, if I run the flatpak from a Terminal (gnome-terminal in this case).

If I run DOSBox-X from the .desktop file, the debugger option is greyed out.

**Comment by rderooy** [comment]
Ok, it was working, but now it is crashing indeed.

**Comment by Jookia** [comment]
Okay, so I did some more testing. Sometimes it does work, sometimes it doesn't. Here are some crash logs:

```
#0  0x00007ffff7bf574c in wnoutrefresh () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#1  0x00007ffff7bf580c in wrefresh () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#2  0x000055555573e2f3 in DBGUI_StartUp () at debug_gui.cpp:623
#3  0x00005555556d9cca in DEBUG_SetupConsole () at debug.cpp:5000
#4  0x0000555555705cc0 in DEBUG_SetupConsole () at debug.cpp:4324
#5  DEBUG_Enable_Handler (pressed=<optimized out>) at debug.cpp:4311
#6  0x0000555555965300 in MAPPER_TriggerEventByName (name=...) at sdl_mapper.cpp:3708
#7  0x0000555555ac53bd in DOSBoxMenu::dispatchItemCommand (this=<optimized out>, item=...) at menu.cpp:1488
#8  0x000055555595d2b7 in HandleMouseButton (button=<optimized out>, motion=<optimized out>) at sdlmain.cpp:4807
#9  0x000055555595e908 in GFX_Events () at sdlmain.cpp:5548
#10 0x00005555556a0db5 in Normal_Loop () at dosbox.cpp:398
#11 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#12 0x0000555555bcfe43 in CALLBACK_RunRealInt (intnum=intnum@entry=22 '\026') at callback.cpp:209
#13 0x00005555557563c9 in device_CON::Read (this=0x55555ba25550, data=0x7fffffffb906 "", size=0x7fffffffb850)
    at /run/build/dosbox-x/src/dos/dev_con.h:732
#14 0x000055555576284e in DOS_ReadFile (entry=<optimized out>, data=data@entry=0x7fffffffb906 "", 
    amount=amount@entry=0x7fffffffb908, fcb=fcb@entry=false) at dos_files.cpp:657
#15 0x00005555558a88e3 in DOS_Shell::InputCommand (this=this@entry=0x55555ba66440, 
    line=line@entry=0x7fffffffbaf0 "") at shell_misc.cpp:486
#16 0x0000555555871a05 in DOS_Shell::Run (this=0x55555ba66440) at shell.cpp:1035
#17 0x00005555558773f2 in SHELL_Run () at shell.cpp:1926
#18 0x0000555555955aa6 in VM_Boot_DOSBox_Kernel () at sdlmain.cpp:7212
#19 0x00005555558fd292 in BIOS::cb_bios_boot__func () at bios.cpp:9731
#20 0x00005555556a0c94 in Normal_Loop () at dosbox.cpp:373
#21 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#22 0x000055555565b101 in main (argc=<optimized out>, argv=0x7fffffffdd38) at sdlmain.cpp:9090


#0  0x00007ffff7bea53e in _nc_waddch_nosync () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#1  0x00007ffff7beb5ac in waddnstr () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#2  0x00007ffff7bf548c in mvwprintw () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#3  0x000055555573cbb1 in DEBUG_RefreshPage (scroll=<optimized out>) at debug_gui.cpp:329
#4  0x0000555555705cc0 in DEBUG_SetupConsole () at debug.cpp:4324
#5  DEBUG_Enable_Handler (pressed=<optimized out>) at debug.cpp:4311
#6  0x0000555555965300 in MAPPER_TriggerEventByName (name=...) at sdl_mapper.cpp:3708
#7  0x0000555555ac53bd in DOSBoxMenu::dispatchItemCommand (this=<optimized out>, item=...) at menu.cpp:1488
#8  0x000055555595d2b7 in HandleMouseButton (button=<optimized out>, motion=<optimized out>) at sdlmain.cpp:4807
#9  0x000055555595e908 in GFX_Events () at sdlmain.cpp:5548
#10 0x00005555556a0db5 in Normal_Loop () at dosbox.cpp:398
#11 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#12 0x0000555555bcfe43 in CALLBACK_RunRealInt (intnum=intnum@entry=22 '\026') at callback.cpp:209
#13 0x00005555557563c9 in device_CON::Read (this=0x55555b9e8430, data=0x7fffffffb906 "", size=0x7fffffffb850)
    at /run/build/dosbox-x/src/dos/dev_con.h:732
#14 0x000055555576284e in DOS_ReadFile (entry=<optimized out>, data=data@entry=0x7fffffffb906 "", 
    amount=amount@entry=0x7fffffffb908, fcb=fcb@entry=false) at dos_files.cpp:657
#15 0x00005555558a88e3 in DOS_Shell::InputCommand (this=this@entry=0x55555b96d8c0, 
    line=line@entry=0x7fffffffbaf0 "") at shell_misc.cpp:486
#16 0x0000555555871a05 in DOS_Shell::Run (this=0x55555b96d8c0) at shell.cpp:1035
#17 0x00005555558773f2 in SHELL_Run () at shell.cpp:1926
#18 0x0000555555955aa6 in VM_Boot_DOSBox_Kernel () at sdlmain.cpp:7212
#19 0x00005555558fd292 in BIOS::cb_bios_boot__func () at bios.cpp:9731
#20 0x00005555556a0c94 in Normal_Loop () at dosbox.cpp:373
#21 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#22 0x000055555565b101 in main (argc=<optimized out>, argv=0x7fffffffdd38) at sdlmain.cpp:9090


#0  0x00007ffff7bea53e in _nc_waddch_nosync () from /usr/lib/x86_64-linux-gnu/libncurses.so.6mm) (0.000 x 0.000 ...
#1  0x00007ffff7beb5ac in waddnstr () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#2  0x00007ffff7bf548c in mvwprintw () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#3  0x00005555556cd7a9 in DrawData () at debug.cpp:964
#4  0x00005555556d435d in DEBUG_DrawScreen () at debug.cpp:4329
#5  0x0000555555705b38 in DEBUG_Enable_Handler (pressed=<optimized out>) at debug.cpp:4314
#6  0x0000555555965300 in MAPPER_TriggerEventByName (name=...) at sdl_mapper.cpp:3708
#7  0x0000555555ac53bd in DOSBoxMenu::dispatchItemCommand (this=<optimized out>, item=...) at menu.cpp:1488
#8  0x000055555595d2b7 in HandleMouseButton (button=<optimized out>, motion=<optimized out>) at sdlmain.cpp:4807
#9  0x000055555595e908 in GFX_Events () at sdlmain.cpp:5548
#10 0x00005555556a0db5 in Normal_Loop () at dosbox.cpp:398
#11 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#12 0x0000555555bcfe43 in CALLBACK_RunRealInt (intnum=intnum@entry=22 '\026') at callback.cpp:209
#13 0x00005555557563c9 in device_CON::Read (this=0x55555b92df50, data=0x7fffffffb906 "", size=0x7fffffffb850)
    at /run/build/dosbox-x/src/dos/dev_con.h:732
#14 0x000055555576284e in DOS_ReadFile (entry=<optimized out>, data=data@entry=0x7fffffffb906 "", 
    amount=amount@entry=0x7fffffffb908, fcb=fcb@entry=false) at dos_files.cpp:657
#15 0x00005555558a88e3 in DOS_Shell::InputCommand (this=this@entry=0x55555b9efbe0, 
    line=line@entry=0x7fffffffbaf0 "") at shell_misc.cpp:486
#16 0x0000555555871a05 in DOS_Shell::Run (this=0x55555b9efbe0) at shell.cpp:1035
#17 0x00005555558773f2 in SHELL_Run () at shell.cpp:1926
#18 0x0000555555955aa6 in VM_Boot_DOSBox_Kernel () at sdlmain.cpp:7212
#19 0x00005555558fd292 in BIOS::cb_bios_boot__func () at bios.cpp:9731
#20 0x00005555556a0c94 in Normal_Loop () at dosbox.cpp:373
#21 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#22 0x000055555565b101 in main (argc=<optimized out>, argv=0x7fffffffdd38) at sdlmain.cpp:9090


#0  0x00007ffff7bf574c in wnoutrefresh () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#1  0x00007ffff7bf580c in wrefresh () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#2  0x000055555573e2f3 in DBGUI_StartUp () at debug_gui.cpp:623
#3  0x00005555556d9cca in DEBUG_SetupConsole () at debug.cpp:5000
#4  0x0000555555705cc0 in DEBUG_SetupConsole () at debug.cpp:4324
#5  DEBUG_Enable_Handler (pressed=<optimized out>) at debug.cpp:4311
#6  0x0000555555965300 in MAPPER_TriggerEventByName (name=...) at sdl_mapper.cpp:3708
#7  0x0000555555ac53bd in DOSBoxMenu::dispatchItemCommand (this=<optimized out>, item=...) at menu.cpp:1488
#8  0x000055555595d2b7 in HandleMouseButton (button=<optimized out>, motion=<optimized out>) at sdlmain.cpp:4807
#9  0x000055555595e908 in GFX_Events () at sdlmain.cpp:5548
#10 0x00005555556a0db5 in Normal_Loop () at dosbox.cpp:398
#11 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#12 0x0000555555bcfe43 in CALLBACK_RunRealInt (intnum=intnum@entry=22 '\026') at callback.cpp:209
#13 0x00005555557563c9 in device_CON::Read (this=0x55555b6a6390, data=0x7fffffffb906 "", size=0x7fffffffb850)
    at /run/build/dosbox-x/src/dos/dev_con.h:732
#14 0x000055555576284e in DOS_ReadFile (entry=<optimized out>, data=data@entry=0x7fffffffb906 "", 
    amount=amount@entry=0x7fffffffb908, fcb=fcb@entry=false) at dos_files.cpp:657
#15 0x00005555558a88e3 in DOS_Shell::InputCommand (this=this@entry=0x55555b9f5240, 
    line=line@entry=0x7fffffffbaf0 "") at shell_misc.cpp:486
#16 0x0000555555871a05 in DOS_Shell::Run (this=0x55555b9f5240) at shell.cpp:1035
#17 0x00005555558773f2 in SHELL_Run () at shell.cpp:1926
#18 0x0000555555955aa6 in VM_Boot_DOSBox_Kernel () at sdlmain.cpp:7212
#19 0x00005555558fd292 in BIOS::cb_bios_boot__func () at bios.cpp:9731
#20 0x00005555556a0c94 in Normal_Loop () at dosbox.cpp:373
#21 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#22 0x000055555565b101 in main (argc=<optimized out>, argv=0x7fffffffdd38) at sdlmain.cpp:9090


#0  0x00007ffff7bea53e in _nc_waddch_nosync () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#1  0x00007ffff7beb5ac in waddnstr () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#2  0x00007ffff7bf548c in mvwprintw () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#3  0x000055555573cbb1 in DEBUG_RefreshPage (scroll=<optimized out>) at debug_gui.cpp:329
#4  0x0000555555705cc0 in DEBUG_SetupConsole () at debug.cpp:4324
#5  DEBUG_Enable_Handler (pressed=<optimized out>) at debug.cpp:4311
#6  0x0000555555965300 in MAPPER_TriggerEventByName (name=...) at sdl_mapper.cpp:3708
#7  0x0000555555ac53bd in DOSBoxMenu::dispatchItemCommand (this=<optimized out>, item=...) at menu.cpp:1488
#8  0x000055555595d2b7 in HandleMouseButton (button=<optimized out>, motion=<optimized out>) at sdlmain.cpp:4807
#9  0x000055555595e908 in GFX_Events () at sdlmain.cpp:5548
#10 0x00005555556a0db5 in Normal_Loop () at dosbox.cpp:398
#11 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#12 0x0000555555bcfe43 in CALLBACK_RunRealInt (intnum=intnum@entry=22 '\026') at callback.cpp:209
#13 0x00005555557563c9 in device_CON::Read (this=0x55555b6931a0, data=0x7fffffffb906 "", size=0x7fffffffb850)
    at /run/build/dosbox-x/src/dos/dev_con.h:732
#14 0x000055555576284e in DOS_ReadFile (entry=<optimized out>, data=data@entry=0x7fffffffb906 "", 
    amount=amount@entry=0x7fffffffb908, fcb=fcb@entry=false) at dos_files.cpp:657
#15 0x00005555558a88e3 in DOS_Shell::InputCommand (this=this@entry=0x55555ba60e50, 
    line=line@entry=0x7fffffffbaf0 "") at shell_misc.cpp:486
#16 0x0000555555871a05 in DOS_Shell::Run (this=0x55555ba60e50) at shell.cpp:1035
#17 0x00005555558773f2 in SHELL_Run () at shell.cpp:1926
#18 0x0000555555955aa6 in VM_Boot_DOSBox_Kernel () at sdlmain.cpp:7212
#19 0x00005555558fd292 in BIOS::cb_bios_boot__func () at bios.cpp:9731
#20 0x00005555556a0c94 in Normal_Loop () at dosbox.cpp:373
#21 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#22 0x000055555565b101 in main (argc=<optimized out>, argv=0x7fffffffdd38) at sdlmain.cpp:9090
```

I also managed to trigger these crashes:

```
#0  __memcmp_avx2_movbe () at ../sysdeps/x86_64/multiarch/memcmp-avx2-movbe.S:413
#1  0x0000555555d40009 in std::char_traits<char>::compare (__n=<optimized out>, 
    __s2=0x5555561b175f "SHELL_CMD_TREE_ERROR", 
    __s1=0x5b9516f0 <error: Cannot access memory at address 0x5b9516f0>)
    at /usr/include/c++/11.3.0/bits/char_traits.h:389
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare (
    __s=__s@entry=0x5555561b175f "SHELL_CMD_TREE_ERROR", this=<optimized out>, this=<optimized out>)
    at /usr/include/c++/11.3.0/bits/basic_string.tcc:1444
#3  0x0000555555d40e48 in std::operator==<char, std::char_traits<char>, std::allocator<char> > (
    __rhs=0x5555561b175f "SHELL_CMD_TREE_ERROR", __lhs=<error: Cannot access memory at address 0x5b9516f0>)
    at /usr/include/c++/11.3.0/bits/basic_string.h:6248
#4  MSG_Add (_name=_name@entry=0x5555561b175f "SHELL_CMD_TREE_ERROR", 
    _val=_val@entry=0x5555561b1746 "No subdirectories exist\n") at messages.cpp:67
#5  0x0000555555877b3b in SHELL_Init () at shell.cpp:1343
#6  0x0000555555955a6e in VM_Boot_DOSBox_Kernel () at sdlmain.cpp:7191
#7  0x00005555558fd292 in BIOS::cb_bios_boot__func () at bios.cpp:9731
#8  0x00005555556a0c94 in Normal_Loop () at dosbox.cpp:373
#9  0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#10 0x000055555565b101 in main (argc=<optimized out>, argv=0x7fffffffdd38) at sdlmain.cpp:9090


#0  0x00007ffff2abd460 in write_cf_list () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so
#1  0x00007ffff2abe786 in nir_serialize () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so
#2  0x00007ffff2c9378d in llvmpipe_update_fs () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so
#3  0x00007ffff2c84568 in llvmpipe_update_derived ()
   from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so
#4  0x00007ffff2c67ce0 in llvmpipe_draw_vbo () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so
#5  0x00007ffff288e879 in vbo_save_playback_vertex_list ()
   from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so
#6  0x00007ffff27174a7 in execute_list () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so
#7  0x00007ffff2746a6d in _mesa_CallList () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so
#8  0x000055555595cba5 in GFX_OpenGLRedrawScreen () at sdlmain.cpp:4741
#9  HandleMouseButton (button=<optimized out>, motion=<optimized out>) at sdlmain.cpp:4713
#10 0x000055555595e908 in GFX_Events () at sdlmain.cpp:5548
#11 0x00005555557053f5 in DEBUG_Loop () at debug.cpp:4170
#12 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#13 0x0000555555bcfe43 in CALLBACK_RunRealInt (intnum=intnum@entry=22 '\026') at callback.cpp:209
#14 0x00005555557563c9 in device_CON::Read (this=0x55555b999560, data=0x7fffffffb906 "", size=0x7fffffffb850)
    at /run/build/dosbox-x/src/dos/dev_con.h:732
#15 0x000055555576284e in DOS_ReadFile (entry=<optimized out>, data=data@entry=0x7fffffffb906 "", 
    amount=amount@entry=0x7fffffffb908, fcb=fcb@entry=false) at dos_files.cpp:657
#16 0x00005555558a88e3 in DOS_Shell::InputCommand (this=this@entry=0x55555b99f1c0, 
    line=line@entry=0x7fffffffbaf0 "") at shell_misc.cpp:486
#17 0x0000555555871a05 in DOS_Shell::Run (this=0x55555b99f1c0) at shell.cpp:1035
#18 0x00005555558773f2 in SHELL_Run () at shell.cpp:1926
#19 0x0000555555955aa6 in VM_Boot_DOSBox_Kernel () at sdlmain.cpp:7212
#20 0x00005555558fd292 in BIOS::cb_bios_boot__func () at bios.cpp:9731
#21 0x00005555556a0c94 in Normal_Loop () at dosbox.cpp:373
#22 0x00005555556a0e86 in DOSBOX_RunMachine () at dosbox.cpp:632
#23 0x000055555565b101 in main (argc=<optimized out>, argv=0x7fffffffdd38) at sdlmain.cpp:9090
```

**Comment by Jookia** [comment]
This doesn't seem to happen with Sdk 20.08. Maybe worth jumping back to that.
