### ISSUE TITLE
Dosbox Crash while copy file with no extension with wildcard

### ISSUE THREAD

**Issue by JulioCouto** [joncampbell123/dosbox-x#3900]
### Describe the bug

Dosbox closes without any message while copy a group of files using wildcards

### Steps to reproduce the behaviour

Create in a  directory of a mounted drive  a file named for example rubros  (without extension) and a file named rubros.idx
run the command:
copy rubros.* corubro.*

then dosbox closes without any meassage.

### What operating system(s) this bug have occurred on?

Dosbox - x over Windows 11

### What version(s) of DOSBox-X have this bug?

v2022.09.0

### Output log

```text
Logging: opened logfile 'C:\DOSBox-X\log.txt' successfully. All further logging will go to this file.
Win32 EnumDisplayDevices #0: name=\\.\DISPLAY1 string=NVIDIA GeForce GT 730
Win32 EnumDisplayDevices #1: name=\\.\DISPLAY2 string=NVIDIA GeForce GT 730
Win32 EnumDisplayDevices #2: name=\\.\DISPLAY3 string=NVIDIA GeForce GT 730
DOSBox-X version 2022.09.0 (Windows SDL1)
Windows keyboard layout ID is 0x380a
Host keyboard layout is now us (US English)
Mapper keyboard layout is now us (US English)
SDL: TTF activated 
Configured windowposition: 
SDL: Windows 11 round corners will be disabled.
Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
ISA BCLK: 8333333.333Hz (25000000/3)
monopal: green, 
Active save slot: 1 [Empty]
USING AVI+ZMBV
Max 3670016 sz 16384
Final 16384
MIDI:fluidsynth: SoundFont not specified
MIDI:synth: Specify .SF2 sound font file with midiconfig=
MT32: failed to locate ROMs.
MT32 emulation requires the PCM and CONTROL ROM files.
To eliminate this error message, check the DOSBox-X wiki.
The ROM files are: CM32L_CONTROL.ROM and CM32L_PCM.ROM or MT32_CONTROL.ROM and MT32_PCM.ROM
MIDI:Opened device:none
Pentium CMPXCHG8B emulation is enabled

Printer Device List
-------------------------------------------------------------
01 OneNote for Windows 10
02 PRN_INFO99 (HP LaserJet P4015)
03 PRN_INFO208 (HP LaserJet P3010 Series)
04 PRN_INFO206 (HP LaserJet P4015)
05 PRN_INFO135 (HP LaserJet P2055dn)
06 Microsoft XPS Document Writer
07 Microsoft Print to PDF
08 KONICA MINOLTA bizhub C221 PCL (192.168.10.93) UPD
09 HP-4015 (HP LaserJet P4015)
10 Fax

Loaded language file: es_ES
VOODOO LFB now at d0000000
Serial1: BASE 3f8h
Serial2: BASE 2f8h
Parallel1: BASE 378h
MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h
Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
Allocated APM BIOS pm entry point at f000:ce40
Writing code to fce40
Writing code to fce60
Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
Windows: IID_ITaskbarList3 is available
ISA Plug & Play BIOS enabled
VGA ROM BIOS init callback
Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
pixratio 1.350, dw false, dh false
Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
SDL: TTF activated 
WARNING: No translation support (to host) for code page 0
Loaded system codepage: 437
Loaded system codepage: 858
DOS keyboard layout loaded with main language code SP for layout sp
XMS: 50 handles allocated for use by the DOS environment
EMS page frame at 0xe000-0xefff
COMMAND.COM env size:             720 bytes
COMMAND.COM environment block:    0xcc01 sz=0x002d
COMMAND.COM main body (PSP):      0xcc2f sz=0x009a
COMMAND.COM stack:                0xcc49
Loaded system codepage: 858
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
This copy operation does not work as you would expect under embedded DOS in dosbox-svn and dosbox-staging either (works as it should in FreeDOS). Unfortunately under dosbox-x it crashes completely. It certainly shouldn't be like that.

Dosbox-x compiled with clang with address sanitizer.

```
shell_cmds.cpp:2542:27: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:150:14: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior shell_cmds.cpp:2542:27 in
AddressSanitizer:DEADLYSIGNAL
=================================================================
==127703==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x5d0f24e16c40 bp 0x7ffc885750f0 sp 0x7ffc88574888 T0)
==127703==The signal is caused by a READ memory access.
==127703==Hint: address points to the zero page.
    #0 0x5d0f24e16c40 in __sanitizer::internal_strlen(char const*) /b/s/w/ir/cache/builder/src/third_party/llvm/compiler-rt/lib/sanitizer_common/sanitizer_libc.cpp:167:10
    #1 0x5d0f24de83b5 in strcat /b/s/w/ir/cache/builder/src/third_party/llvm/compiler-rt/lib/asan/asan_interceptors.cpp:388:26
    #2 0x5d0f25e86e6b in DOS_Shell::CMD_COPY(char*) /tmp/dosbox-x/src/shell/shell_cmds.cpp:2542:8
    #3 0x5d0f25ed5294 in DOS_Shell::execute_shell_cmd(char*, char*) /tmp/dosbox-x/src/shell/shell_cmds.cpp:240:4
    #4 0x5d0f25ed2b8a in DOS_Shell::DoCommand(char*) /tmp/dosbox-x/src/shell/shell_cmds.cpp:292:6
    #5 0x5d0f25e245a9 in DOS_Shell::ParseLine(char*) /tmp/dosbox-x/src/shell/shell.cpp:548:2
    #6 0x5d0f25e402bb in DOS_Shell::Run() /tmp/dosbox-x/src/shell/shell.cpp:1068:4
    #7 0x5d0f25e4b5f6 in SHELL_Run() /tmp/dosbox-x/src/shell/shell.cpp:1948:16
    #8 0x5d0f266c4c80 in VM_Boot_DOSBox_Kernel() /tmp/dosbox-x/src/gui/sdlmain.cpp:7391:9
    #9 0x5d0f264067ee in BIOS::cb_bios_boot__func() /tmp/dosbox-x/src/ints/bios.cpp:9817:14
    #10 0x5d0f24e3f130 in Normal_Loop() /tmp/dosbox-x/src/dosbox.cpp:373:33
    #11 0x5d0f24e3f9ae in DOSBOX_RunMachine() /tmp/dosbox-x/src/dosbox.cpp:632:13
    #12 0x5d0f266f35ee in main /tmp/dosbox-x/src/gui/sdlmain.cpp:9292:13
    #13 0x760f96c3c28f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)
    #14 0x760f96c3c349 in __libc_start_main (/usr/lib/libc.so.6+0x23349) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)
    #15 0x5d0f24d66f54 in _start /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
```
