### ISSUE TITLE
Windows 95/98 with core=normal and non-recursive page fault handling crashes with GPF when it attempts to go fullscreen to an MS-DOS box 

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#65]
I'm guessing this has something to do with I/O port trapping and DOSBox's callback function-based INT 10h emulation combined with the non-recursive page fault.

Windows 3.1 and Windows NT 3.1 don't seem to have this issue.

**Comment by joncampbell123** [comment]
Stack trace of the page fault, when entering fullscreen mode, Win95, machine=svga_s3:

#0  PageFaultCore () at paging.cpp:110
#1  0x08058692 in Normal_Loop () at dosbox.cpp:343
#2  0x08058d1e in DOSBOX_RunMachine () at dosbox.cpp:503
#3  0x08109140 in PAGING_NewPageFault (lin_addr=lin_addr@entry=659456, page_addr=<optimized out>, faultcode=faultcode@entry=6, prepare_only=false) at paging.cpp:336
#4  0x0810acb0 in PAGING_NewPageFault (faultcode=6, prepare_only=false, page_addr=<optimized out>, lin_addr=659456) at paging.cpp:277
#5  InitPage (prepare_only=false, writing=true, lin_addr=659456, this=0x9e4625c <init_page_handler>) at paging.cpp:729
#6  NewInitPageHandler::writeb (this=0x9e4625c <init_page_handler>, addr=659456, val=0) at paging.cpp:653
#7  0x080b043c in mem_writeb_inline (val=<optimized out>, address=659456) at ../../include/paging.h:317
#8  mem_memcpy (dest=659457, src=794369, size=<optimized out>) at memory.cpp:253
#9  0x080b0605 in MEM_BlockCopy (dest=dest@entry=659456, src=794368, size=size@entry=16) at memory.cpp:313
#10 0x082b51e0 in INT10_LoadFont (font=<optimized out>, reload=reload@entry=true, count=count@entry=256, offset=offset@entry=0, map=map@entry=0, height=16) at int10_memory.cpp:61
#11 0x082b53f8 in INT10_ReloadFont () at int10_memory.cpp:106
#12 0x082b8ce5 in INT10_SetVideoMode (mode=<optimized out>) at int10_modes.cpp:1633
#13 0x082b1d37 in INT10_Handler () at int10.cpp:54
#14 0x080586b5 in Normal_Loop () at dosbox.cpp:375
#15 0x08058d1e in DOSBOX_RunMachine () at dosbox.cpp:503
#16 0x08054c9d in main (argc=1, argv=0xbffffc04) at sdlmain.cpp:4014

**Comment by joncampbell123** [comment]
Also noted: If the system is paging heavily (like Windows 98) and you attempt to bring up a DOS box, the screen will freeze.

**Comment by joncampbell123** [comment]
Hm, suppose it's something wrong with the full core?

**Comment by joncampbell123** [comment]
Fixed.

Apparently the problem was that opcode 0x8F (POP [memory location]) would trigger a page fault during the fullscreen switch, and DOSBox's normal core did not contain code to reset the stack pointer so that the instruction could be retried after the page fault.

**Comment by joncampbell123** [comment]
Not quite. Win95 is OK, Win98 is OK, WinME is OK. Only Win95 OSR2 still has problems entering fullscreen.
