### ISSUE TITLE
Windows ME gets stuck in an INT 13 VM86 call on third reboot

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#67]
Backtrace of stuck call.
#0  mem_readb_inline (address=3221267004) at ../../include/paging.h:294
#1  0x08118a84 in Fetchb () at core_normal.cpp:122
#2  CPU_Core_Normal_Run () at core_normal/prefix_66.h:321
#3  0x08058662 in Normal_Loop () at dosbox.cpp:343
#4  0x08058cee in DOSBOX_RunMachine () at dosbox.cpp:503
#5  0x080f4cc8 in CALLBACK_RunRealFar (seg=61440, off=1792) at callback.cpp:110
#6  0x080f919f in CPU_ForceV86FakeIO_In (port=503, len=len@entry=1) at cpu.cpp:3085
#7  0x080d961c in IDE_SelfIO_In (port=<optimized out>, len=len@entry=1, ide=<optimized out>) at ide.cpp:2203
#8  0x080d9ebd in IDE_EmuINT13DiskReadByBIOS (disk=128 '\200', cyl=0, head=12, sect=44) at ide.cpp:2465
#9  0x082c6c45 in INT13_DiskHandler () at bios_disk.cpp:500
#10 0x08058685 in Normal_Loop () at dosbox.cpp:375
#11 0x08058cee in DOSBOX_RunMachine () at dosbox.cpp:503
#12 0x08054c6d in main (argc=1, argv=0xbf8a0864) at sdlmain.cpp:4014

It did not exit the loop. This seems to be problem with I/O port trapping, Windows ME, the non-reentrant page fault code, and the IDE vm86 hack. The I/O port in question was port 1F7 read access (IDE status). Is our vm86 hack getting stuck waiting for status bits that WinME virtualization never change?

Temporary workaround: Install Windows ME with the ISA PnP BIOS enabled (isapnpbios=true), make sure the IDE controller is set to show up in PnP enumeration (pnp=true), and disable the vm86 hack (int13fakev86io=false). This will of course cause Windows ME to flag the IDE controller as faulty since the vm86 test does not pass, but it lets WinME boot.

Edit: Dumping the value returned by WinME virtualization for port 1F7h shows 0xFF when the real I/O port would return status!

Edit: On second thought, just remove the IDE controller from PnP enumeration and reenable the ide vm86 io hack. You may have to use Add New Hardware wizard.

The stuck loop in question:

```
                                            do {
                                                    /* TODO: Timeout needed */
                                                    unsigned int i = IDE_SelfIO_In(ide,ide->base_io+7,1);
                                                    if ((i&0x80) == 0) break;
                                            } while (1);
```

So.... is Windows ME virtualization failing to toggle ready bit?

Perhaps the fix is to enforce a timeout in this loop?

**Comment by joncampbell123** [comment]
Digging deeper; for some reason a flag is not set in the ME kernel IDE driver that "allows" it to carry through the IDE read. It checks the flag, which is not set, then branches to a return path that returns 0xFF.

Not sure why.

**Comment by joncampbell123** [comment]
I ran the source code back through the commits and found the issue started with Windows ME right when I added the adaptive IDE alt I/O port allocation not to collide with the FDC. Having an alignment of 4 isn't right... I'll see if fixing the alignment fixes the problem with Windows ME.

**Comment by joncampbell123** [comment]
Ah, disabling FDC emulation seems to fix the issue.
So, is this some kind of resource conflict between IDE and FDC because of I/O port 3F6?
How did Windows ME deal with this on real hardware?

**Comment by joncampbell123** [comment]
...nope.

**Comment by joncampbell123** [comment]
A reinstall test of Windows ME suggests that this mysterious IDE problem has disappeared on it's own... will check.

**Comment by joncampbell123** [comment]
Apparently Windows ME is OK with the IDE emulation now, though it's not happy with the APM emulation for some reason.
