### ISSUE TITLE
Winnt 3.1: switching DOS to fullscreen with machine=svga_et4000 causes segfault in DOSBox VGA drawing code

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#70]
Program received signal SIGSEGV, Segmentation fault.
VGA_Draw_1BPP_Line_as_VGA (vidstart=384000, line=0) at vga_draw.cpp:232
232         val=pixels.b[0];
(gdb) backtrace
#0  VGA_Draw_1BPP_Line_as_VGA (vidstart=384000, line=0) at vga_draw.cpp:232
#1  0x080edf5a in VGA_DrawSingleLine () at vga_draw.cpp:1068
#2  0x080b85d7 in PIC_RunQueue () at pic.cpp:546
#3  0x0805863d in Normal_Loop () at dosbox.cpp:326
#4  0x08058d1e in DOSBOX_RunMachine () at dosbox.cpp:503
#5  0x08054c9d in main (argc=1, argv=0xbffffc04) at sdlmain.cpp:4014

**Comment by joncampbell123** [comment]
It no longer crashes.

**Comment by joncampbell123** [comment]
Whoops! Windows NT 3.1, not Windows 3.1!

**Comment by joncampbell123** [comment]
Recent testing: Windows 3.1 is *generally* able to go fullscreen with et4000 emulation, but sometimes leaving fullscreen will mess up the display a bit (with a warning message from Windows).
