### ISSUE TITLE
El Torito floppy emulation segfault

### ISSUE THREAD

**Issue by chriscjs** [joncampbell123/dosbox-x#742]
Host is Arch Linux.  Dosbox-x version is 0.82.7.  All dosbox.conf settings are at default.
Using the following commands in dosbox:
    imgmount d: win98se.iso -t iso -fs none
    imgmount 0 -el-torito d: -t floppy -fs none
As soon as the second command is given, dosbox quits unexpectedly and the console output says segfault.
The win98se.iso boots fine in qemu and vmware.  Here is the console debugging output:

LOG: 1735905773 DEBUG EXEC:Parsing command line: imgmount d: win98se.iso -t iso -fs none
LOG: 1735905776       EXEC:Execute imgmount.COM 0
LOG: 1735905776       FILES:file open command 0 file imgmount.COM
LOG: 1735905776 DEBUG MISC:DOS_AllocateMemory(blocks=0x0045) = 0x08ca-0x090e
LOG: 1735905776 DEBUG MISC:DOS_AllocateMemory(blocks=0x96ef) = 0x0910-0x9ffe
LOG: 1735905783 DEBUG MISC:DOS_ResizeMemory(seg=0x0910) blocks=0x0040
LOG: IDE: index 0 slave=0
LOG: 1735905786       MISC:MSCDEX: Mounting iso file as cdrom: win98se.iso
LOG: 1735905786 DEBUG DOSMISC:DOS_GetMemory(0x0002 pages,"MSCDEX device header") = 0xc304
LOG: 1735905786 DEBUG DOSMISC:DOS_GetMemory(0x0126 pages,"MSCDEX temp buffer") = 0xc306
LOG: 1846128343 DEBUG EXEC:Parsing command line: imgmount 0 -el-torito d: -t floppy -fs none
LOG: 1846128346       EXEC:Execute imgmount.COM 0
LOG: 1846128346       FILES:file open command 0 file imgmount.COM
LOG: 1846128346 DEBUG MISC:DOS_AllocateMemory(blocks=0x0045) = 0x08ca-0x090e
LOG: 1846128346 DEBUG MISC:DOS_AllocateMemory(blocks=0x96ef) = 0x0910-0x9ffe
LOG: 1846128353 DEBUG MISC:DOS_ResizeMemory(seg=0x0910) blocks=0x0040
LOG: El Torito emulation: Found ISO 9660 Boot Record in sector 17, pointing to sector 20
LOG: El Torito entry: first header platform=0x00
LOG: El Torito entry: bootable x86 record mediatype=2 load_segment=0x0000 system_type=0x00 sector_count=1 load_rba=21
LOG: IDE: index -1 slave=0
Segmentation fault (core dumped)

**Comment by joncampbell123** [comment]
Debug trace, on my system:

IMGMOUNT::Run (this=0x433e2c0) at dos_programs.cpp:2665
2665	                    WriteOut(MSG_Get("PROGRAM_IMGMOUNT_MOUNT_NUMBER"), drive - '0', paths[0].c_str());
(gdb) backtrace
#0  IMGMOUNT::Run (this=0x433e2c0) at dos_programs.cpp:2665
#1  0x00000000004b811a in PROGRAMS_Handler () at programs.cpp:132
#2  0x000000000041b9de in Normal_Loop () at dosbox.cpp:364
#3  0x000000000041c18e in DOSBOX_RunMachine () at dosbox.cpp:513
#4  0x0000000000667c9d in CALLBACK_RunRealInt (intnum=intnum@entry=33 '!') at callback.cpp:165
#5  0x0000000000488413 in DOS_Shell::Execute (this=this@entry=0x433df80, name=name@entry=0x7fffffffba50 "imgmount", 
    args=args@entry=0x7fffffffcb68 " 0 -el-torito d: -t floppy -fs none") at shell_misc.cpp:834
#6  0x000000000048339b in DOS_Shell::DoCommand (this=this@entry=0x433df80, line=0x7fffffffcb68 " 0 -el-torito d: -t floppy -fs none", 
    line@entry=0x7fffffffcb60 "imgmount 0 -el-torito d: -t floppy -fs none") at shell_cmds.cpp:179
#7  0x000000000047baa6 in DOS_Shell::ParseLine (this=this@entry=0x433df80, 
    line=line@entry=0x7fffffffcb60 "imgmount 0 -el-torito d: -t floppy -fs none") at shell.cpp:272
#8  0x000000000047cf80 in DOS_Shell::Run (this=0x433df80) at shell.cpp:373
#9  0x000000000047cbfb in SHELL_Run () at shell.cpp:1043
#10 0x00000000004db233 in VM_Boot_DOSBox_Kernel () at sdlmain.cpp:6850
#11 0x00000000004a7769 in BIOS::cb_bios_boot__func () at bios.cpp:6696
#12 0x000000000041b9de in Normal_Loop () at dosbox.cpp:364
#13 0x000000000041c18e in DOSBOX_RunMachine () at dosbox.cpp:513
#14 0x00000000004145ca in main (argc=<optimized out>, argv=<optimized out>) at sdlmain.cpp:8252

**Comment by joncampbell123** [comment]
Pull the latest commit, compile, and try it now.

**Comment by chriscjs** [comment]
Thanks, that worked!
